local wow_env = require("spec.helpers.wow_env")

local function new_env()
  local env = wow_env.new({ presets = {
    [62] = { { name = "Desired", selections = { [100] = 1002 } } },
  } })
  env.traits.delayed = true
  return env
end

describe("asynchronous Folio commits", function()
  it("a deleted profile invalidates its captured completion", function()
    local env = new_env()
    env.ns.profile_store.save(62, "Editable", { [100] = 1002 })
    env.ns.actions.apply("Editable")
    env.ns.profile_store.delete(62, "Editable")
    env.traits.complete(true)
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(0, #env.timers)
  end)

  it("queues the new spec in combat using committed rather than staged selections", function()
    local env = new_env()
    env.ns.profile_store.save(63, "New spec", { [100] = 1002 })
    env.ns.profile_store.set_active(63, "New spec")
    env.ns.swap_controller.request_apply()
    env.spec_id = 63
    env.in_combat = true
    env.ns.swap_controller.on_event("PLAYER_SPECIALIZATION_CHANGED", "player")
    assert.is_true(env.ns.swap_controller.pending)
    env.traits.complete(false)
    env.run_timers()
    env.in_combat = false
    env.ns.swap_controller.on_event("PLAYER_REGEN_ENABLED")
    assert.equals(2, env.traits.commits)
    env.traits.complete(true)
    env.run_timers()
    assert.equals(2, #env.messages)
    assert.matches('Profile "New spec" applied', env.messages[2])
  end)

  it("ignores unrelated trait events and cannot confirm using staged selections even when ready", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    env.traits.ready = true
    env.ns.swap_controller.on_event("TRAIT_CONFIG_UPDATED", 99)
    env.ns.swap_controller.on_event("CONFIG_COMMIT_FAILED", 99)
    env.ns.swap_controller.on_event("PLAYER_SPECIALIZATION_CHANGED", "party1")
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(1, env.traits.commits)
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("applied", env.messages[1])
  end)

  it("a conflicting external edit after acceptance is never rolled back on timeout", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    env.traits.complete(true)
    C_Traits.SetSelection(7, 200, 2002)
    for _ = 1, 20 do env.run_timers() end
    assert.equals(1, #env.messages)
    assert.matches("not confirmed", env.messages[1])
    assert.equals(2002, env.traits.nodes[200].active)
    assert.equals(2001, env.traits.nodes[200].committed)
    assert.equals(0, env.traits.rollbacks)
    assert.equals(1, env.traits.commits)
  end)

  it("manual supersession while busy never reports the older completion", function()
    local env = new_env()
    env.ns.profile_store.save(62, "Other", { [100] = 1001 })
    env.ns.actions.apply("Desired")
    env.ns.actions.apply("Other")
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("still saving", env.messages[1])
    assert.equals(1, env.traits.commits)
    assert.equals(0, #env.timers)
  end)

  it("the new spec receives its own bounded busy retry and completion", function()
    local env = new_env()
    env.ns.profile_store.save(63, "New spec", { [100] = 1001 })
    env.ns.profile_store.set_active(63, "New spec")
    env.ns.swap_controller.request_apply()
    env.spec_id = 63
    env.ns.swap_controller.on_event("PLAYER_SPECIALIZATION_CHANGED", "player")
    env.traits.complete(true)
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(2, env.traits.commits)
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches('Profile "New spec" applied', env.messages[1])
    assert.equals(0, #env.timers)
  end)

  it("pending API results contain no applied nodes", function()
    local env = new_env()
    local result = env.ns.folio_api.apply({ [100] = 1002 })
    assert.equals("pending", result.reason)
    assert.same({}, result.applied)
    env.traits.complete(false)
    local final = env.ns.folio_api.verify(result)
    assert.equals("commit_failed", final.reason)
    assert.same({}, final.applied)
    assert.is_nil(final.pending)
  end)

  it("an accepted automatic request invalidates an older retry callback", function()
    local env = new_env()
    env.traits.ready = false
    env.ns.swap_controller.request_apply()
    env.traits.ready = true
    env.ns.swap_controller.request_apply()
    env.run_timers()
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("applied", env.messages[1])
    assert.equals(1, env.traits.commits)
    assert.equals(0, #env.timers)
  end)

  it("does not claim profile success if a previously matching requested row changes externally", function()
    local env = new_env()
    env.ns.profile_store.save(62, "Two rows", { [100] = 1002, [200] = 2001 })
    env.ns.actions.apply("Two rows")
    env.traits.nodes[200].active = 2002
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("Could not save", env.messages[1])
    assert.equals(0, env.traits.rollbacks)
  end)

  it("config replacement ends verification without reading or rolling back the old config", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    C_Traits.GetConfigIDBySystemID = function() return 99 end
    env.run_timers()
    assert.equals(0, #env.timers)
    assert.equals(0, env.traits.rollbacks)
    assert.equals(1, #env.messages)
    assert.matches("Could not save", env.messages[1])
  end)

  it("an overwritten profile invalidates its captured completion", function()
    local env = new_env()
    env.ns.profile_store.save(62, "Editable", { [100] = 1002 })
    env.ns.actions.apply("Editable")
    env.ns.profile_store.save(62, "Editable", { [100] = 1001 })
    env.traits.complete(true)
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(0, #env.timers)
  end)

  it("an automatic request stops reporting after the active assignment changes", function()
    local env = new_env()
    env.ns.profile_store.save(62, "Other", { [100] = 1001 })
    env.ns.swap_controller.request_apply()
    env.ns.profile_store.set_active(62, "Other")
    env.traits.complete(true)
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(0, #env.timers)
  end)

  it("save current reads committed runes rather than an in-flight staged profile", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    env.ns.actions.save_current("Snapshot")
    assert.equals(1001, env.ns.profile_store.get(62, "Snapshot").selections[100])
  end)

  it("does not commit or roll back another editor's staged selections", function()
    local env = new_env()
    C_Traits.SetSelection(7, 200, 2002)
    env.ns.actions.apply("Desired")
    assert.equals(0, env.traits.commits)
    assert.equals(1, #env.traits.set_calls)
    assert.equals(0, env.traits.rollbacks)
    assert.matches("can't be changed", env.messages[1])
  end)

  it("a manual apply cancels an older automatic busy retry", function()
    local env = new_env()
    env.traits.delayed = false
    env.ns.profile_store.save(62, "Manual", { [100] = 1001 })
    env.traits.ready = false
    env.ns.swap_controller.request_apply()
    env.traits.ready = true
    env.ns.actions.apply("Manual")
    env.run_timers()
    assert.equals(0, env.traits.commits)
    assert.equals(1, #env.messages)
    assert.matches("already active", env.messages[1])
    assert.equals(0, #env.timers)
  end)

  it("checks spec identity even before its event arrives", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    env.spec_id = 63
    env.traits.complete(true)
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(0, #env.timers)
  end)

  it("a spec change to no profile invalidates the old request", function()
    local env = new_env()
    env.ns.swap_controller.request_apply()
    env.spec_id = 63
    env.ns.swap_controller.on_event("PLAYER_SPECIALIZATION_CHANGED", "player")
    env.traits.complete(true)
    env.run_timers()
    assert.same({}, env.messages)
    assert.equals(0, #env.timers)
    assert.equals(1, env.traits.commits)
  end)

  it("a new manual request supersedes the previous completion report", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    env.traits.complete(true)
    env.ns.actions.apply("Desired")
    assert.equals(1, #env.messages)
    assert.matches("already active", env.messages[1])
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.equals(0, #env.timers)
  end)

  it("bounds unresolved commits to twenty half-second polls and ignores late success", function()
    local env = new_env()
    local delays, after = {}, C_Timer.After
    C_Timer.After = function(delay, callback)
      delays[#delays + 1] = delay
      after(delay, callback)
    end
    env.ns.actions.apply("Desired")
    for _ = 1, 19 do env.run_timers() end
    assert.same({}, env.messages)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("not confirmed", env.messages[1])
    assert.equals(20, #delays)
    for _, delay in ipairs(delays) do assert.equals(0.5, delay) end
    assert.equals(0, #env.timers)
    assert.equals(0, env.traits.rollbacks)
    assert.equals(1, env.traits.commits)
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
  end)

  it("reports asynchronous rejection once without rollback or resubmission", function()
    local env = new_env()
    env.ns.swap_controller.request_apply()
    env.traits.complete(false)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("Could not save", env.messages[1])
    assert.equals(0, #env.timers)
    assert.equals(0, env.traits.rollbacks)
    assert.equals(1, env.traits.commits)
  end)

  it("reports delayed success only after committed selection readback", function()
    local env = new_env()
    env.ns.actions.apply("Desired")
    assert.equals(1002, C_Traits.GetNodeInfo(7, 100).activeEntry.entryID)
    assert.same({ 1001 }, C_Traits.GetNodeInfo(7, 100).entryIDsWithCommittedRanks)
    assert.same({}, env.messages)
    env.run_timers()
    assert.same({}, env.messages)
    env.traits.complete(true)
    env.run_timers()
    assert.equals(1, #env.messages)
    assert.matches("applied", env.messages[1])
    assert.equals(1, env.traits.commits)
    assert.equals(0, #env.timers)
  end)
end)
